-- 025_seed_ai_tags_catalog.sql
-- Expande o catálogo de tags de IA (idempotente via ON CONFLICT slug).

insert into public.tags (slug, name)
values
  -- Já existentes (garante nome canônico)
  ('chatgpt', 'ChatGPT'),
  ('claude', 'Claude'),
  ('gemini', 'Gemini'),
  ('openai', 'OpenAI'),
  ('anthropic', 'Anthropic'),
  ('google', 'Google'),
  ('meta', 'Meta'),
  ('microsoft', 'Microsoft'),
  ('lancamento', 'Lançamento'),
  ('pesquisa', 'Pesquisa'),
  ('empresas', 'Empresas'),
  ('brasil', 'Brasil'),
  ('api', 'API'),
  ('codigo', 'Código'),
  ('imagem', 'Imagem'),
  ('prompting', 'Prompting'),

  -- Modelos, labs e produtos
  ('llm', 'LLM'),
  ('modelo-fronteira', 'Modelo de fronteira'),
  ('modelo-aberto', 'Modelo aberto'),
  ('codigo-aberto', 'Código aberto'),
  ('deepseek', 'DeepSeek'),
  ('xai', 'xAI'),
  ('grok', 'Grok'),
  ('llama', 'Llama'),
  ('mistral', 'Mistral'),
  ('cohere', 'Cohere'),
  ('perplexity', 'Perplexity'),
  ('apple', 'Apple'),
  ('amazon', 'Amazon'),
  ('nvidia', 'NVIDIA'),
  ('hugging-face', 'Hugging Face'),
  ('stability-ai', 'Stability AI'),
  ('midjourney', 'Midjourney'),
  ('copilot', 'Copilot'),
  ('cursor', 'Cursor'),
  ('sora', 'Sora'),
  ('veo', 'Veo'),
  ('qwen', 'Qwen'),

  -- Capacidades e modalidades
  ('ia-generativa', 'IA generativa'),
  ('multimodal', 'Multimodal'),
  ('raciocinio', 'Raciocínio'),
  ('agentes', 'Agentes'),
  ('agentic-ai', 'Agentic AI'),
  ('voz', 'Voz'),
  ('audio', 'Áudio'),
  ('video', 'Vídeo'),
  ('visao-computacional', 'Visão computacional'),
  ('ocr', 'OCR'),
  ('traducao', 'Tradução'),
  ('busca', 'Busca'),
  ('rag', 'RAG'),
  ('embeddings', 'Embeddings'),
  ('world-models', 'World models'),
  ('robotica', 'Robótica'),
  ('ia-fisica', 'IA física'),

  -- Engenharia e infra
  ('fine-tuning', 'Fine-tuning'),
  ('treinamento', 'Treinamento'),
  ('inferencia', 'Inferência'),
  ('tokens', 'Tokens'),
  ('contexto-longo', 'Contexto longo'),
  ('gpu', 'GPU'),
  ('chip', 'Chip'),
  ('semicondutores', 'Semicondutores'),
  ('data-center', 'Data center'),
  ('cloud', 'Cloud'),
  ('on-device', 'On-device'),
  ('edge', 'Edge'),
  ('quantizacao', 'Quantização'),
  ('serving', 'Serving'),
  ('mcp', 'MCP'),
  ('tool-use', 'Tool use'),
  ('avaliacao', 'Avaliação'),
  ('benchmark', 'Benchmark'),
  ('dataset', 'Dataset'),
  ('dados-sinteticos', 'Dados sintéticos'),

  -- Produto, trabalho e mercado
  ('assistente', 'Assistente'),
  ('copilotos', 'Copilotos'),
  ('produtividade', 'Produtividade'),
  ('automacao', 'Automação'),
  ('enterprise', 'Enterprise'),
  ('startup', 'Startup'),
  ('investimento', 'Investimento'),
  ('aquisicao', 'Aquisição'),
  ('parceria', 'Parceria'),
  ('precificacao', 'Precificação'),
  ('open-vs-closed', 'Open source vs closed'),
  ('talento', 'Talento'),
  ('concorrencia', 'Concorrência'),

  -- Segurança, ética e regulação
  ('seguranca', 'Segurança'),
  ('alinhamento', 'Alinhamento'),
  ('guardrails', 'Guardrails'),
  ('privacidade', 'Privacidade'),
  ('lgpd', 'LGPD'),
  ('regulacao', 'Regulação'),
  ('pl-2338', 'PL 2338'),
  ('governanca', 'Governança'),
  ('transparencia', 'Transparência'),
  ('copyright', 'Copyright'),
  ('deepfake', 'Deepfake'),
  ('desinformacao', 'Desinformação'),
  ('ciberseguranca', 'Cibersegurança'),
  ('jailbreak', 'Jailbreak'),
  ('prompt-injection', 'Prompt injection'),
  ('soberania-digital', 'Soberania digital'),
  ('setor-publico', 'Setor público'),

  -- Setores / aplicação
  ('educacao', 'Educação'),
  ('saude', 'Saúde'),
  ('financas', 'Finanças'),
  ('direito', 'Direito'),
  ('marketing', 'Marketing'),
  ('atendimento', 'Atendimento'),
  ('ciencia', 'Ciência'),
  ('clima', 'Clima'),
  ('mobilidade', 'Mobilidade'),
  ('jogos', 'Jogos'),
  ('midia', 'Mídia'),
  ('agricultura', 'Agricultura'),

  -- Geografia / ecossistema
  ('china', 'China'),
  ('eua', 'EUA'),
  ('uniao-europeia', 'União Europeia'),
  ('ai-act', 'AI Act'),
  ('america-latina', 'América Latina'),
  ('sao-paulo', 'São Paulo'),

  -- Formato editorial
  ('analise', 'Análise'),
  ('tutorial', 'Tutorial'),
  ('entrevista', 'Entrevista'),
  ('opiniao', 'Opinião'),
  ('rumores', 'Rumores'),
  ('atualizacao', 'Atualização'),
  ('breaking', 'Breaking')
on conflict (slug) do update set
  name = excluded.name;
