-- 026_seed_ai_subjects_catalog.sql
-- Seed de assuntos (subjects) a partir do catálogo editorial de IA.
-- Idempotente via ON CONFLICT (slug).

insert into public.subjects (slug, name, summary, status)
values
  ('agentes', 'Agentes', 'Agentes autônomos e orquestração de ferramentas.', 'published'),
  ('agentic-ai', 'Agentic AI', 'Sistemas de IA agentic capazes de agir com ferramentas.', 'published'),
  ('ai-act', 'AI Act', 'Regulação europeia de inteligência artificial (AI Act).', 'published'),
  ('alinhamento', 'Alinhamento', 'Assunto editorial sobre Alinhamento no contexto de inteligência artificial.', 'published'),
  ('amazon', 'Amazon', 'Empresa e serviços de IA da Amazon (incl. AWS).', 'published'),
  ('america-latina', 'América Latina', 'Assunto editorial sobre América Latina no contexto de inteligência artificial.', 'published'),
  ('analise', 'Análise', 'Assunto editorial sobre Análise no contexto de inteligência artificial.', 'published'),
  ('anthropic', 'Anthropic', 'Empresa focada em IA segura e Claude.', 'published'),
  ('api', 'API', 'Assunto editorial sobre API no contexto de inteligência artificial.', 'published'),
  ('apple', 'Apple', 'Empresa e iniciativas de IA da Apple.', 'published'),
  ('aquisicao', 'Aquisição', 'Assunto editorial sobre Aquisição no contexto de inteligência artificial.', 'published'),
  ('assistente', 'Assistente', 'Assunto editorial sobre Assistente no contexto de inteligência artificial.', 'published'),
  ('atendimento', 'Atendimento', 'Assunto editorial sobre Atendimento no contexto de inteligência artificial.', 'published'),
  ('atualizacao', 'Atualização', 'Assunto editorial sobre Atualização no contexto de inteligência artificial.', 'published'),
  ('audio', 'Áudio', 'Assunto editorial sobre Áudio no contexto de inteligência artificial.', 'published'),
  ('automacao', 'Automação', 'Assunto editorial sobre Automação no contexto de inteligência artificial.', 'published'),
  ('avaliacao', 'Avaliação', 'Assunto editorial sobre Avaliação no contexto de inteligência artificial.', 'published'),
  ('benchmark', 'Benchmark', 'Assunto editorial sobre Benchmark no contexto de inteligência artificial.', 'published'),
  ('brasil', 'Brasil', 'Notícias e iniciativas de IA no Brasil.', 'published'),
  ('breaking', 'Breaking', 'Assunto editorial sobre Breaking no contexto de inteligência artificial.', 'published'),
  ('busca', 'Busca', 'Assunto editorial sobre Busca no contexto de inteligência artificial.', 'published'),
  ('chatgpt', 'ChatGPT', 'Assistente conversacional da OpenAI.', 'published'),
  ('china', 'China', 'Assunto editorial sobre China no contexto de inteligência artificial.', 'published'),
  ('chip', 'Chip', 'Assunto editorial sobre Chip no contexto de inteligência artificial.', 'published'),
  ('ciberseguranca', 'Cibersegurança', 'Assunto editorial sobre Cibersegurança no contexto de inteligência artificial.', 'published'),
  ('ciencia', 'Ciência', 'Assunto editorial sobre Ciência no contexto de inteligência artificial.', 'published'),
  ('claude', 'Claude', 'Família de modelos da Anthropic.', 'published'),
  ('cloud', 'Cloud', 'Assunto editorial sobre Cloud no contexto de inteligência artificial.', 'published'),
  ('codigo', 'Código', 'Assunto editorial sobre Código no contexto de inteligência artificial.', 'published'),
  ('codigo-aberto', 'Código aberto', 'Assunto editorial sobre Código aberto no contexto de inteligência artificial.', 'published'),
  ('cohere', 'Cohere', 'Empresa de modelos e plataformas de LLM.', 'published'),
  ('concorrencia', 'Concorrência', 'Assunto editorial sobre Concorrência no contexto de inteligência artificial.', 'published'),
  ('contexto-longo', 'Contexto longo', 'Assunto editorial sobre Contexto longo no contexto de inteligência artificial.', 'published'),
  ('copilot', 'Copilot', 'Assistente de IA da Microsoft.', 'published'),
  ('copilotos', 'Copilotos', 'Assunto editorial sobre Copilotos no contexto de inteligência artificial.', 'published'),
  ('copyright', 'Copyright', 'Assunto editorial sobre Copyright no contexto de inteligência artificial.', 'published'),
  ('cursor', 'Cursor', 'IDE com assistência de IA para desenvolvimento.', 'published'),
  ('dados-sinteticos', 'Dados sintéticos', 'Assunto editorial sobre Dados sintéticos no contexto de inteligência artificial.', 'published'),
  ('data-center', 'Data center', 'Assunto editorial sobre Data center no contexto de inteligência artificial.', 'published'),
  ('dataset', 'Dataset', 'Assunto editorial sobre Dataset no contexto de inteligência artificial.', 'published'),
  ('deepfake', 'Deepfake', 'Assunto editorial sobre Deepfake no contexto de inteligência artificial.', 'published'),
  ('deepseek', 'DeepSeek', 'Lab chinês e modelos de linguagem DeepSeek.', 'published'),
  ('desinformacao', 'Desinformação', 'Assunto editorial sobre Desinformação no contexto de inteligência artificial.', 'published'),
  ('direito', 'Direito', 'Assunto editorial sobre Direito no contexto de inteligência artificial.', 'published'),
  ('edge', 'Edge', 'Assunto editorial sobre Edge no contexto de inteligência artificial.', 'published'),
  ('educacao', 'Educação', 'Assunto editorial sobre Educação no contexto de inteligência artificial.', 'published'),
  ('embeddings', 'Embeddings', 'Assunto editorial sobre Embeddings no contexto de inteligência artificial.', 'published'),
  ('empresas', 'Empresas', 'Assunto editorial sobre Empresas no contexto de inteligência artificial.', 'published'),
  ('enterprise', 'Enterprise', 'Assunto editorial sobre Enterprise no contexto de inteligência artificial.', 'published'),
  ('entrevista', 'Entrevista', 'Assunto editorial sobre Entrevista no contexto de inteligência artificial.', 'published'),
  ('eua', 'EUA', 'Assunto editorial sobre EUA no contexto de inteligência artificial.', 'published'),
  ('financas', 'Finanças', 'Assunto editorial sobre Finanças no contexto de inteligência artificial.', 'published'),
  ('fine-tuning', 'Fine-tuning', 'Assunto editorial sobre Fine-tuning no contexto de inteligência artificial.', 'published'),
  ('gemini', 'Gemini', 'Família de modelos de IA do Google.', 'published'),
  ('google', 'Google', 'Empresa e ecossistema de produtos de IA do Google.', 'published'),
  ('governanca', 'Governança', 'Assunto editorial sobre Governança no contexto de inteligência artificial.', 'published'),
  ('gpu', 'GPU', 'Assunto editorial sobre GPU no contexto de inteligência artificial.', 'published'),
  ('grok', 'Grok', 'Modelo e assistente de IA da xAI.', 'published'),
  ('guardrails', 'Guardrails', 'Assunto editorial sobre Guardrails no contexto de inteligência artificial.', 'published'),
  ('hugging-face', 'Hugging Face', 'Plataforma e ecossistema open source de ML/IA.', 'published'),
  ('ia-fisica', 'IA física', 'Assunto editorial sobre IA física no contexto de inteligência artificial.', 'published'),
  ('ia-generativa', 'IA generativa', 'Assunto editorial sobre IA generativa no contexto de inteligência artificial.', 'published'),
  ('imagem', 'Imagem', 'Assunto editorial sobre Imagem no contexto de inteligência artificial.', 'published'),
  ('inferencia', 'Inferência', 'Assunto editorial sobre Inferência no contexto de inteligência artificial.', 'published'),
  ('investimento', 'Investimento', 'Assunto editorial sobre Investimento no contexto de inteligência artificial.', 'published'),
  ('jailbreak', 'Jailbreak', 'Assunto editorial sobre Jailbreak no contexto de inteligência artificial.', 'published'),
  ('jev', 'JEV', 'Assunto editorial sobre JEV no contexto de inteligência artificial.', 'published'),
  ('jogos', 'Jogos', 'Assunto editorial sobre Jogos no contexto de inteligência artificial.', 'published'),
  ('lancamento', 'Lançamento', 'Assunto editorial sobre Lançamento no contexto de inteligência artificial.', 'published'),
  ('lgpd', 'LGPD', 'Lei Geral de Proteção de Dados Pessoais no Brasil.', 'published'),
  ('llama', 'Llama', 'Família de modelos abertos da Meta.', 'published'),
  ('llm', 'LLM', 'Modelos de linguagem de grande escala.', 'published'),
  ('marketing', 'Marketing', 'Assunto editorial sobre Marketing no contexto de inteligência artificial.', 'published'),
  ('mcp', 'MCP', 'Model Context Protocol para integração de ferramentas com IA.', 'published'),
  ('meta', 'Meta', 'Empresa e modelos de IA da Meta (Llama e outros).', 'published'),
  ('microsoft', 'Microsoft', 'Empresa e produtos de IA da Microsoft.', 'published'),
  ('midia', 'Mídia', 'Assunto editorial sobre Mídia no contexto de inteligência artificial.', 'published'),
  ('midjourney', 'Midjourney', 'Plataforma de geração de imagens por IA.', 'published'),
  ('mistral', 'Mistral', 'Lab europeu e modelos de linguagem da Mistral.', 'published'),
  ('mobilidade', 'Mobilidade', 'Assunto editorial sobre Mobilidade no contexto de inteligência artificial.', 'published'),
  ('modelo-aberto', 'Modelo aberto', 'Assunto editorial sobre Modelo aberto no contexto de inteligência artificial.', 'published'),
  ('modelo-fronteira', 'Modelo de fronteira', 'Assunto editorial sobre Modelo de fronteira no contexto de inteligência artificial.', 'published'),
  ('multimodal', 'Multimodal', 'Modelos que combinam texto, imagem, áudio e vídeo.', 'published'),
  ('nvidia', 'NVIDIA', 'Empresa de GPUs e infraestrutura para IA.', 'published'),
  ('ocr', 'OCR', 'Assunto editorial sobre OCR no contexto de inteligência artificial.', 'published'),
  ('on-device', 'On-device', 'Assunto editorial sobre On-device no contexto de inteligência artificial.', 'published'),
  ('open-vs-closed', 'Open source vs closed', 'Assunto editorial sobre Open source vs closed no contexto de inteligência artificial.', 'published'),
  ('openai', 'OpenAI', 'Empresa por trás do GPT e do ChatGPT.', 'published'),
  ('opiniao', 'Opinião', 'Assunto editorial sobre Opinião no contexto de inteligência artificial.', 'published'),
  ('parceria', 'Parceria', 'Assunto editorial sobre Parceria no contexto de inteligência artificial.', 'published'),
  ('perplexity', 'Perplexity', 'Motor de busca e assistente com IA.', 'published'),
  ('pesquisa', 'Pesquisa', 'Assunto editorial sobre Pesquisa no contexto de inteligência artificial.', 'published'),
  ('pl-2338', 'PL 2338', 'Projeto de lei brasileiro sobre inteligência artificial.', 'published'),
  ('precificacao', 'Precificação', 'Assunto editorial sobre Precificação no contexto de inteligência artificial.', 'published'),
  ('privacidade', 'Privacidade', 'Assunto editorial sobre Privacidade no contexto de inteligência artificial.', 'published'),
  ('produtividade', 'Produtividade', 'Assunto editorial sobre Produtividade no contexto de inteligência artificial.', 'published'),
  ('prompt-injection', 'Prompt injection', 'Assunto editorial sobre Prompt injection no contexto de inteligência artificial.', 'published'),
  ('prompting', 'Prompting', 'Assunto editorial sobre Prompting no contexto de inteligência artificial.', 'published'),
  ('quantizacao', 'Quantização', 'Assunto editorial sobre Quantização no contexto de inteligência artificial.', 'published'),
  ('qwen', 'Qwen', 'Família de modelos de IA da Alibaba.', 'published'),
  ('raciocinio', 'Raciocínio', 'Assunto editorial sobre Raciocínio no contexto de inteligência artificial.', 'published'),
  ('rag', 'RAG', 'Retrieval-Augmented Generation e recuperação de contexto.', 'published'),
  ('regulacao', 'Regulação', 'Políticas, leis e governança de inteligência artificial.', 'published'),
  ('robotica', 'Robótica', 'Assunto editorial sobre Robótica no contexto de inteligência artificial.', 'published'),
  ('rumores', 'Rumores', 'Assunto editorial sobre Rumores no contexto de inteligência artificial.', 'published'),
  ('seguranca', 'Segurança', 'Assunto editorial sobre Segurança no contexto de inteligência artificial.', 'published'),
  ('semicondutores', 'Semicondutores', 'Assunto editorial sobre Semicondutores no contexto de inteligência artificial.', 'published'),
  ('serving', 'Serving', 'Assunto editorial sobre Serving no contexto de inteligência artificial.', 'published'),
  ('setor-publico', 'Setor público', 'Assunto editorial sobre Setor público no contexto de inteligência artificial.', 'published'),
  ('soberania-digital', 'Soberania digital', 'Assunto editorial sobre Soberania digital no contexto de inteligência artificial.', 'published'),
  ('sora', 'Sora', 'Modelo de geração de vídeo da OpenAI.', 'published'),
  ('stability-ai', 'Stability AI', 'Empresa por trás de modelos de geração de imagem.', 'published'),
  ('startup', 'Startup', 'Assunto editorial sobre Startup no contexto de inteligência artificial.', 'published'),
  ('talento', 'Talento', 'Assunto editorial sobre Talento no contexto de inteligência artificial.', 'published'),
  ('tokens', 'Tokens', 'Assunto editorial sobre Tokens no contexto de inteligência artificial.', 'published'),
  ('tool-use', 'Tool use', 'Assunto editorial sobre Tool use no contexto de inteligência artificial.', 'published'),
  ('traducao', 'Tradução', 'Assunto editorial sobre Tradução no contexto de inteligência artificial.', 'published'),
  ('transparencia', 'Transparência', 'Assunto editorial sobre Transparência no contexto de inteligência artificial.', 'published'),
  ('treinamento', 'Treinamento', 'Assunto editorial sobre Treinamento no contexto de inteligência artificial.', 'published'),
  ('tutorial', 'Tutorial', 'Assunto editorial sobre Tutorial no contexto de inteligência artificial.', 'published'),
  ('uniao-europeia', 'União Europeia', 'Assunto editorial sobre União Europeia no contexto de inteligência artificial.', 'published'),
  ('veo', 'Veo', 'Modelo de geração de vídeo do Google.', 'published'),
  ('video', 'Vídeo', 'Assunto editorial sobre Vídeo no contexto de inteligência artificial.', 'published'),
  ('visao-computacional', 'Visão computacional', 'Assunto editorial sobre Visão computacional no contexto de inteligência artificial.', 'published'),
  ('voz', 'Voz', 'Assunto editorial sobre Voz no contexto de inteligência artificial.', 'published'),
  ('world-models', 'World models', 'Assunto editorial sobre World models no contexto de inteligência artificial.', 'published'),
  ('xai', 'xAI', 'Empresa de IA fundada por Elon Musk.', 'published')
on conflict (slug) do update set
  name = excluded.name,
  summary = excluded.summary,
  status = excluded.status;
